### ISSUE TITLE
[UI Bug] Mark/Unmark Homework not updating the side window (Homework list) in real time

### ISSUE THREAD

**Issue by fahim-tazz** [AY2223S2-CS2103T-W13-4/tp#65] opened 2023-03-16 09:21 UTC
While the Homework List of a student is open (on the right side), marking the homework as DONE does not instantly update the status on the Homework List. I have to click on the Homework button again to refresh the Homework List.

See the screenshots for details:

![Before mark as DONE](https://user-images.githubusercontent.com/86123134/225571725-7374f850-7679-4f83-8969-6d042ea989f8.png)

![After mark as DONE](https://user-images.githubusercontent.com/86123134/225571836-1d181393-a39e-48f7-bed9-d0efa6bfe36e.png)

PS: Not urgent for v1.2

**Comment by fahim-tazz** [comment] 2023-03-16 09:23
Possible solution:
After mark/unmark is done successfully, just automatically call the HomeWork button handler method, this will always reopen the right side panel.

**Comment by fahim-tazz** [comment] 2023-03-16 09:53
The same issue is with Lessons button. Adding a lesson does not show up immediately on the Lesson window on the right side (I have to click Lessons button).

**Comment by Yufannnn** [comment] 2023-03-22 01:08
This is not a bug, but rather an intended behaviour. The detailed information section and the command box functionality are designed to be completely separate and are not intended to interact with each other. As such, we have made a conscious decision not to introduce any interaction between the two features, as this could potentially result in significant changes to the codebase and increase the risk of introducing bugs.

**Comment by Yufannnn** [comment] 2023-03-22 05:31
This bug should still be fixed in some way

**Comment by Yufannnn** [comment] 2023-03-22 05:32
Fixed with the new merge

**Closed as completed by Yufannnn** 2023-03-22 05:32 UTC
Labels: bug, priority.Low
